### ISSUE TITLE
Chapter Titles should have leading dots to page number

### ISSUE THREAD

**Issue by TheShadow29** [cardi/USCthesis#5]
I got the comment: "Table of Contents: Every entry on the TOC needs leading dots going to each page number."

This can be fixed by adding the following line here: https://github.com/cardi/USCthesis/blob/v1.4.2/USCthesis.sty#L985

```
\renewcommand{\cftchapleader}{\cftdotfill{\cftdotsep}}
```

**Comment by cardi** [comment]
This should be there, see line 969 and 974 (previously fixed in https://github.com/cardi/USCthesis/pull/4): https://github.com/cardi/USCthesis/blob/ad640c5a791b30426b76dc6191542d7d1afd98ae/USCthesis.sty#L965-L975

Could you verify that you're using the latest version of `USCthesis.sty`?

**Comment by TheShadow29** [comment]
Ah, my bad. I was using this version "Revision 1.4.1  2022/06/16 00:00:00  Calvin Ardi", seems like the latest is 1.4.2

Closing the issue then.
